annodomini/annodomini/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic.simple import redirect_to
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from filebrowser.sites import site
from annodomini import settings
from annodomini.team.models import Person
from annodomini.news.views import NewsDetailView, NewsRedirectView
from annodomini.projects.views import ProjectDetailView, CategoryDetailView as ProjectCategoryDetailView,\
    ProjectsRedirectView
from annodomini.team.views import PersonDetailView

admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(
        template_name="base.html"
    )),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    (r'^about/$', redirect_to, {'url': '/about/history/'}),
    (r'^about/team/$', ListView.as_view(
        model=Person,
        context_object_name="person_list",
    )),
    (r'^about/team/(?P<slug>[-\w]+)/$', PersonDetailView.as_view()),
    (r'^news/$', NewsRedirectView.as_view()),
    (r'^news/(?P<slug>[-\w]+)/$', 'news.views.news_list'),
    (r'^news/(?P<category__name>[-\w]+)/(?P<slug>[-\w]+)/$', NewsDetailView.as_view()),
    (r'^projects/$', ProjectsRedirectView.as_view()),
    (r'^projects/(?P<slug>[-\w]+)/$', ProjectCategoryDetailView.as_view()),
    (r'^projects/(?P<category__name>[-\w]+)/(?P<slug>[-\w]+)/$', 
        ProjectDetailView.as_view()),
    url(r'', include('django.contrib.flatpages.urls')),
)

annodomini/annodomini/news/models.py
import datetime
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField
from easy_thumbnails.files import get_thumbnailer
from annodomini.util.fields import WYSIWYGField

class Category(models.Model):
    name = models.CharField(max_length=250)       
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "Categories"
    
    def __unicode__(self):
        return self.name

class News(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    thumbnail = ThumbnailerImageField(
        upload_to='news/thumbnail',
        resize_source=dict(size=(140, 105), crop='smart'),
    )
    date = models.DateField(default=datetime.datetime.now)
    category = models.ForeignKey(Category, related_name='news')
    preliminary_text = WYSIWYGField(blank=True, null=True)
    main_text = WYSIWYGField(blank=True, null=True)
    
    class Meta:
        verbose_name_plural = "News"
    
    def __unicode__(self):
        return self.name
    
class Photo(models.Model):
    image = models.ImageField(upload_to='news/photo')
    comment = models.CharField(max_length=250, blank=True, null=True)
    project = models.ForeignKey(News, related_name='photos', verbose_name="news")
    order = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        ordering = ['project', 'order']
   
    def normal_view(self):
        """
        This is a helper thumbnail shown in admin
        """
        thumbnailer = get_thumbnailer(self.image, relative_name=self.image.name)
        thumb = thumbnailer.get_thumbnail({'size': (100, 0)})        
            
        return thumb.tag()
       
    normal_view.allow_tags = True
    
    def __unicode__(self):
        return str(self.image.url.split("/")[-1])

annodomini/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Anno Domini™{% endblock %}</title>
	<meta charset="UTF-8" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<link rel="shortcut icon" href="favicon.ico" />
	<link href='http://fonts.googleapis.com/css?family=Poiret+One|Open+Sans:600italic,600,400italic,400&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
	{% block extra_styles %}{% endblock %}
	{% block background_styles %}
		{% if background %}
		<link rel="stylesheet" type="text/css" href="/static/css/{{ background.style }}" />
		{% endif %}
	{% endblock %}
	<script type="text/javascript" src="/static/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery.mousewheel.js"></script>
	<script type="text/javascript" src="/static/js/jquery.jscrollpane.min.js"></script>
	<script type="text/javascript" src="/static/js/site.js"></script>
	{% block extra_scripts %}{% endblock %}
</head>
<body>
	<div id="header">
		<div id="logo"><a href="/"><img src="/static/img/logo.png" alt="Anno Domini" width="200" height="106" /></a></div>
		{% block main_menu %}
		<div id="header-bar">
			<ul id="nav-main">
			{% load util_tags %}
				<li><a href="/" id="{% active request "^$" %}"></a></li>
				<li><a href="/about/" id="{% active request "^/about/" %}">О компании</a></li>
				<li><a href="/news/" id="{% active request "^/news/" %}">Новости</a></li>
				<li><a href="/projects/" id="{% active request "^/projects/" %}">Фильмы</a></li>
				<li><a href="/production/" id="{% active request "^/production/$" %}">Production</a></li>
				<li><a href="/product-placement/" id="{% active request "^/product-placement/$" %}">Product Placement</a></li>
			</ul>
		</div>
		{% endblock %}
	</div>
{% block sub_menu %}{% endblock %}
{% block content %}
	<div id="index-spacer"></div>
{% endblock %}
{% block arrows %}{% endblock %}
{% block background %}
	
	<div id="background">
		
		<img src="{% if background %}{{ background.preloader.url }}{% else %}/static/img/default.png{% endif %}" id="bg-picture" />
		<div id="overlay"></div>

		{% if background %}
		<div class="video_background">
			<video autoplay loop muted poster="{{ background.preloader.url }}" id="bg-video">
			{% if background.video_mp4 %}
				<source src="{{ background.video_mp4.url }}" type="video/mp4" />
			{% endif %}
			{% if background.video_ogg %}
				<source src="{{ background.video_ogg.url }}" type="video/ogg" />
			{% endif %}
			{% if background.video_webm %}
				<source src="{{ background.video_webm.url }}" type="video/webm" />
			{% endif %}
				<img src="{{ background.preloader.url }}" id="bg-video-poster" />
			</video>
		</div>
		{% endif %}
		<div id="bg-medium"></div>
	</div>
{% endblock %}
{% block footer %}
	<div id="footer">
		<a href="#" id="toggleContent" title="Галерея"></a>
	</div>
{% endblock %}
</body>
</html>

annodomini/templates/base_about.html
{% extends "base.html" %}

{% block title %}Anno domini - о компании{% endblock %}
{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="/static/css/padder-about.css" />
{% endblock %}
{% block sub_menu %}
{% endblock %}
{% block content %}
{% endblock %}

annodomini/templates/subnav_about.html
<div id="sub-nav">
	<ul>					
		{% load util_tags %}
		<li><a href="/about/history/" id="{% active request "^/about/history/$" %}">История</a></li>
        <li><a href="/about/team/" id="{% active request "^/about/team/" %}">Команда</a></li>
        <li><a href="/about/contact/" id="{% active request "^/about/contact/$" %}">Контактная информация</a></li>
	</ul>
</div>

annodomini/templates/subnav_news.html
<div id="sub-nav">
	<ul>					
		{% load util_tags %}
		{% for category in category_list %}
		<li>
			<a href="/news/{{ category.slug }}/" id="{% active_news_category request category.slug %}">
				{{ category.name }}
			</a>
		</li>
        {% endfor %}
	</ul>
</div>

annodomini/templates/subnav_project.html
<div id="sub-nav">
	<ul>					
		{% load util_tags %}
		{% for category in category_list %}
		<li>
			<a href="/projects/{{ category.slug }}/" id="{% active_project_category request category.slug %}">
				{{ category.name }}
			</a>
		</li>
        {% endfor %}
	</ul>
</div>